language: ruby
rvm:
- 2.1.1
cache: bundler
script: echo "Nothing to build."
deploy:
  provider: s3
  access_key_id: AKIAIZY56TD54JM32ZFA
  secret_access_key:
    secure: n34fM601G3MAlrsIAv7sRL+LQ430CPWSr1cNobyoRScWHUcOKtqvNhT6B2ZXYSyFp4Jiv/DrLpsBLjft5cYG+k3Ixhm4xgxKkF747uu2dudNcMDlygMVeaXpSnmWwpsasABMYUoKEdMBBdKh65K/RuUgO+YHuzGbJ3W4mCSESPs=
  on:
    repo: afeld/api.afeld.me
    branch: travis
  skip_cleanup: true
