name: Run tests

on: push

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3
          bundler-cache: true
      - name: Run tests
        run: bundle exec rspec

  tenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: true
      - name: Sync Python dependencies
        run: uv sync

      - name: Install pip in project environment
        run: uv pip install pip

      - name: Install spaCy model
        run: uv run python -m spacy download en_core_web_sm

      - name: Check tenses
        run: uv run pytest
